name: action-deploy
description: Action to manage GitHub deployments
author: radiantspace
inputs:
  token:
    required: true
    description: GitHub token
  type:
    required: true
    description: a type of deployment action to perform, can be 'create', 'delete', 'delete-all' and 'status'
  logs:
    required: false
    description: url to deployment logs
  description:
    required: false
    description: description of a deployment
  deployment_id:
    required: false
    description: an id for deployment if 'delete' or 'status' type is used
runs:
  using: 'node12'
  main: 'dist/index.js'
